# Generated by Django 5.0.6 on 2024-06-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='./videos/'),
        ),
    ]
