# Generated by Django 5.0.6 on 2024-06-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='AntonymSynonymExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=50)),
                ('video_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonym_synonym_video_1', to='myapp.video')),
                ('video_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonym_synonym_video_2', to='myapp.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrammarExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=50)),
                ('video_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_video_1', to='myapp.video')),
                ('video_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_video_2', to='myapp.video')),
                ('video_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_video_3', to='myapp.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdiomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=50)),
                ('video_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiom_video_1', to='myapp.video')),
                ('video_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiom_video_2', to='myapp.video')),
                ('video_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiom_video_3', to='myapp.video')),
                ('video_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiom_video_4', to='myapp.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PronunciationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=50)),
                ('video_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_video_1', to='myapp.video')),
                ('video_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_video_2', to='myapp.video')),
                ('video_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_video_3', to='myapp.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VocabularyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_1', models.CharField(max_length=50)),
                ('word_2', models.CharField(max_length=50)),
                ('question_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(max_length=255)),
                ('options_1', models.JSONField()),
                ('options_2', models.JSONField()),
                ('correct_option_1', models.CharField(max_length=50)),
                ('correct_option_2', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_video', to='myapp.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
