# Generated by Django 5.0.6 on 2024-06-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_video_video_file_antonymsynonymexercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_before_blank', models.TextField()),
                ('part_after_blank', models.TextField()),
                ('options', models.JSONField()),
                ('missing_word', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FITBE_video', to='myapp.video')),
            ],
        ),
    ]
