# Generated by Django 5.0.6 on 2024-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fillintheblankexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblankexercise',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='antonymsynonymexercise',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fillintheblankexercise',
            name='part_after_blank',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fillintheblankexercise',
            name='part_before_blank',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='grammarexercise',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='idiomexercise',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pronunciationexercise',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabularyexercise',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
