# Generated by Django 5.0.6 on 2024-06-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fillintheblankexercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillintheblankexercise',
            old_name='missing_word',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='grammarexercise',
            old_name='correct_option',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='idiomexercise',
            old_name='correct_option',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='vocabularyexercise',
            old_name='correct_option_1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='vocabularyexercise',
            old_name='correct_option_2',
            new_name='answer_2',
        ),
    ]
