# Generated by Django 5.0.6 on 2024-06-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_missing_word_fillintheblankexercise_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessTheTranslationOfTheWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=255)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_the_traslation', to='myapp.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
