# Generated by Django 5.0.6 on 2024-06-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_guessthetranslationoftheword'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessthetranslationoftheword',
            name='eng_word',
            field=models.CharField(default='', max_length=255),
        ),
    ]
