# Generated by Django 5.0.6 on 2024-06-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_guessthetranslationoftheword_eng_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularyexercise',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='vocabularyexercise',
            name='options_2',
        ),
        migrations.RemoveField(
            model_name='vocabularyexercise',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='vocabularyexercise',
            name='word_2',
        ),
    ]
