# Generated by Django 5.0.6 on 2024-06-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_vocabularyexercise_answer_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularyexercise',
            old_name='answer_1',
            new_name='answer',
        ),
    ]
