# Generated by Django 5.0.6 on 2024-06-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_vocabularyexercise_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PronunciationExercise',
        ),
    ]
